// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Transaction struct {
	Reference *string `json:"reference,omitempty"`
}

func (o *Transaction) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}
